
DataProClass: DataProLog
#DataProClass: DataProMedian
Framework: Seq2Seq

command: run_train

kf: 0
epochs: 1000

save_freq: 1
#load_len: &load_len 1000
load_len: &load_len -1
hidden_size: &hidden_size 100
batch_size: &batch_size 64
rnn_layers: &rnn_layers 1
rnn_dropout: &rnn_dropout 0.5
bidirectional: &bidirectional True

DataPro:
  #raw_data_file: ../input/train_1.csv
  raw_data_file: ../input/train_2.csv
  load_len: *load_len
  batch_size: *batch_size
  k_fold: 20
  col_start: 430
  target_type: 1

encoder: &encoder
  #type: simple
  type: pa3
  input_size: 1
  hidden_size: *hidden_size
  n_layers: *rnn_layers
  dropout: *rnn_dropout
  bidirectional: *bidirectional
  activation_rate: 0.2
  optimizer: {type: Adam, l2_scale: 0.0, beta1: 0.9, beta2: 0.99, epsilon: 0.00000001}

decoder: &decoder
  type: simple
  output_size: 1
  hidden_size: *hidden_size
  n_layers: *rnn_layers
  dropout: *rnn_dropout
  bidirectional: *bidirectional
  optimizer: {type: Adam, l2_scale: 0.0, beta1: 0.9, beta2: 0.99, epsilon: 0.00000001}


Model:
  enc_file: ~
  #enc_file: wtf_2017-09-04_13-20-01-898433_ae5_enc.pth
  #enc_freeze_span: [0, 1]

  dec_file: ~
  #dec_file: wtf_2017-08-31_09-26-15-817563_kf0_1_dec.pth

  loss_fn: SMAPE
  encoder: *encoder
  decoder: *decoder

  teacher_forcing_ratio: 0.5
  keep_hidden: False
  clip: 5.0
  lr: 0.001
  train_batch_per_epoch: 8000
  #train_batch_per_epoch: 3000
  validate_batch_per_epoch: 500






